### ISSUE TITLE
Mendel's first law problem in http://rosalind.info/problems/iprb/  proposal

### ISSUE THREAD

**Issue by edgar-mtz-e** [Superbest/RosalindNet#1]
public static double computeProbabilityMendel (double k, double m, double n)
        { 
            double t=0, p=0;
            t = k + m + n;
            p += k * (k - 1 + m + n);
            p += m * (k + 0.75 * (m - 1) + 0.5 * n);
            p += n * (k + 0.5 * m);
            p /= t * (t - 1);
            return p;        
        }
        public static string Iprb(string input)
        {
            string[] ss = input.Split(' ');
            return computeProbabilityMendel(double.Parse(ss[0]), double.Parse(ss[1]), double.Parse(ss[2])).ToString();
        }

**Comment by Superbest** [comment]
This method works, however I think my implementation is a bit clearer, so I'll stick with that.

It turns out my own implementation hadn't been working because I made a mistake when parsing the input, not because of a problem in the algorithm. Commit c7f29bd should have the working version (I tried to do the Rosalind problems 3 times and all 3 were correct).
